name: build and scan
description: Trivy scan image
inputs:
  image_name:
    description: "Name of the image that is going to be pushed"
    required: true
  image_repository_username:
    description: "The username of the image repository account"
    required: true
  image_repository_password:
    description: "The password of the image repository account"
    required: true
  image_version:
    description: "Version of the image that is going to be pushed"
    required: true
  registry:
    description: "Registry to push the image to"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.image_repository_username }}
        password: ${{ inputs.image_repository_password }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0
      with:
        version: latest
    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: ${{inputs.image_name}}:${{ inputs.image_version }}
        push: false
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{inputs.image_name}}:${{ inputs.image_version }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '0'
        ignore-unfixed: false
    - name: Upload Trivy scan results to GitHub
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'