name: Promote Image
description: Promote Image
inputs:
  docker_username:
    description: "The username of the docker account"
    required: true
  docker_password:
    description: "The password of the docker account"
    required: true
  image_version:
    description: "Version of the image that is going to be promoted"
    required: true
  original_image_repository:
    description: "Name of the repository where the image is going to be promoted from"
    required: true
  target_image_repository:
    description: "Name of the repository where the image is going to be promoted to"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Pull image from source registry
      shell: bash
      run: |
        docker pull ${{ inputs.docker_username}}/${{ inputs.original_image_repository }}:${{ inputs.image_version }}

    - name: push image to target registry
      shell: bash
      run: |
        docker push ${{ inputs.docker_username }}/${{ inputs.target_image_repository }}:${{ inputs.image_version }}

