name: Promote Image
description: Promote Image
inputs:
  image_repository_username:
    description: "The username of the docker account"
    required: true
  image_repository_password:
    description: "The password of the docker account"
    required: true
  image_version:
    description: "Version of the image that is going to be promoted"
    required: true
  original_image_repository:
    description: "Name of the repository where the image is going to be promoted from"
    required: true
  target_image_repository:
    description: "Name of the repository where the image is going to be promoted to"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.image_repository_username }}
        password: ${{ inputs.image_repository_password }}

    - name: Pull and push image from source registry
      shell: bash
      run: |
        docker pull ${{ inputs.image_repository_username}}/${{ inputs.original_image_repository }}:${{ inputs.image_version }}
        docker image tag ${{ inputs.image_repository_username}}/${{ inputs.original_image_repository }}:${{ inputs.image_version }} ${{ inputs.image_repository_username }}/${{ inputs.target_image_repository }}:${{ inputs.image_version }}
        docker push ${{ inputs.image_repository_username }}/${{ inputs.target_image_repository }}:${{ inputs.image_version }}


      

