name: Promote Image
description: Promote Image
inputs:
  image_repository_username:
    description: "The username of the docker account"
    required: true
  image_repository_password:
    description: "The password of the docker account"
    required: true
  image_version:
    description: "Version of the image that is going to be promoted"
    required: true
  original_image:
    description: "Name of the image that is going to be promoted"
    required: true
  target_image:
    description: "Name of the new image that is going to be promoted"
    required: true
  registry:
    description: "Registry to push the image to"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.image_repository_username }}
        password: ${{ inputs.image_repository_password }}

    - name: Pull and push image from source registry
      shell: bash
      run: |
        docker pull ${{ inputs.original_image }}:${{ inputs.image_version }}
        docker image tag ${{ inputs.original_image }}:${{ inputs.image_version }} ${{ inputs.target_image }}:${{ inputs.image_version }}
        docker push ${{ inputs.target_image }}:${{ inputs.image_version }}


      

