name: Extract Tag Test
description: Extracts the previous tag from the repository
outputs:
  tag:
    description: "The current tag of the application"
    value: ${{ steps.tag.outputs.tag }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Previous Tag
      id: get_tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - name: Display Tag
      shell: bash
      run: echo "The most recent tag is ${{ steps.get_tag.outputs.tag }}"
    - name: Output tag
      id: tag
      shell: bash
      run: |
        tag_name="${{ steps.get_tag.outputs.tag }}"
        tag_number="${tag_name#"v"}"
        echo "::set-output name=version_number::$version_number"
        echo "tag=${{ tag_number }}" >> "$GITHUB_OUTPUT"