name: Extract Tag Test
description: Extracts the previous tag from the repository
outputs:
  tag:
    description: "The current tag of the application"
    value: ${{ steps.tag.outputs.tag }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Previous Tag
      id: get_tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - name: Output tag
      id: tag
      shell: bash
      run: |
        echo "tag=${{ steps.get_tag.outputs.tag }}" >> $GITHUB_OUTPUT