name: Push Image
description: Push Image
inputs:
  image_name:
    description: "Name of the image that is going to be pushed"
    required: true
  docker_username:
    description: "The username of the docker account"
    required: true
  docker_password:
    description: "The password of the docker account"
    required: true
  image_version:
    description: "Version of the image that is going to be pushed"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0
      with:
        version: latest

    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ inputs.docker_username }}/${{inputs.image_name}}:${{ inputs.image_version }}