name: CI Workflow

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - 'metrics/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - 'metrics/**'


jobs:  
  extract_tag_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/extract-tag

  load-env-file:
    runs-on: ubuntu-latest
    outputs:
      github_infra_repo_username: ${{ steps.variables.outputs.github_infra_repo_username }}
      github_infra_repo_name: ${{ steps.variables.outputs.github_infra_repo_name }}
      github_application_repo_commit_username: ${{ steps.variables.outputs.github_application_repo_commit_username }}
      github_application_repo_commit_user_email: ${{ steps.variables.outputs.github_application_repo_commit_user_email }}
      dora_metrics: ${{ steps.variables.outputs.dora_metrics }}
    steps:
      - uses: actions/checkout@v4
      - id: variables
        uses: ./.github/workflows/load-env-file
        with:
          path: ./pipeline_env_variables
          mode: development

  calculate-metrics:
    runs-on: ubuntu-latest
    needs: [load-env-file]
    environment: development
    if: ${{ needs.load-env-file.outputs.dora_metrics == 'TRUE' }}
    steps:
      - uses: actions/checkout@v4
      - name: Update image tag in infrastructure repository
        uses: ./.github/workflows/dora-metrics
        with:
          github_application_repo_commit_username: ${{needs.load-env-file.outputs.github_application_repo_commit_username}}
          github_application_repo_commit_user_email: ${{needs.load-env-file.outputs.github_application_repo_commit_user_email}}
          github_access_token: ${{ secrets.GHA_TOKEN }}
          branch: ${{ github.ref }}

  build:
    runs-on: ubuntu-latest
    outputs:
      semantic_version: ${{ steps.calculate-version.outputs.version-string }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: master
          create_tag: true
      - name: Use version
        run: | 
          echo "Calculated version: ${{ steps.calculate-version.outputs.version-string }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
          version: latest

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-world-flask:${{ needs.build.outputs.semantic_version }}
          
  update-helm-values:
    runs-on: ubuntu-latest
    needs: [push, build,load-env-file]
    steps:
      - uses: actions/checkout@v4
      - name: Update image tag in infrastructure repository
        uses: ./.github/workflows/update-infrastructure-repository
        with:
          github_infra_repo_username: ${{needs.load-env-file.outputs.github_infra_repo_username}}
          github_infra_repo_name: ${{needs.load-env-file.outputs.github_infra_repo_name}}
          github_application_repo_commit_username: ${{needs.load-env-file.outputs.github_application_repo_commit_username}}
          github_application_repo_commit_user_email: ${{needs.load-env-file.outputs.github_application_repo_commit_user_email}}
          github_access_token: ${{ secrets.GHA_TOKEN }}
          image_version: ${{ needs.build.outputs.semantic_version }}

