name: CI Workflow

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - 'metrics/**'
      - 'pipeline_env_variables/**'

jobs:
  load-env-file:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.variables.outputs.environment }}
      github_infra_repo_username: ${{ steps.variables.outputs.github_infra_repo_username }}
      github_infra_repo_name: ${{ steps.variables.outputs.github_infra_repo_name }}
      github_application_repo_commit_username: ${{ steps.variables.outputs.github_application_repo_commit_username }}
      github_application_repo_commit_user_email: ${{ steps.variables.outputs.github_application_repo_commit_user_email }}
      dora_metrics: ${{ steps.variables.outputs.dora_metrics }}
      image_name: ${{ steps.variables.outputs.image_name }}

    steps:
      - uses: actions/checkout@v4
      - id: variables
        uses: ./.github/actions/load-env-file
        with:
          path: ./pipeline_env_variables
          mode: development

  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calculate-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: calculate-version
        uses: ./.github/actions/calculate-version
        with:
          create_tag: true
          branch: ${{ github.ref_name  }}

  build:
    runs-on: ubuntu-latest
    needs: calculate-version
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-image
        with:
          docker_username: ${{ secrets.IMAGE_REPOSITORY_USERNAME }}
          docker_password: ${{ secrets.IMAGE_REPOSITORY_PASSWORD }}

  push:
    runs-on: ubuntu-latest
    needs: [calculate-version, build,load-env-file]
    steps:
      - uses: actions/checkout@v4
      - name: push to image registry
        uses: ./.github/actions/push-image
        with:
          image_name: ${{needs.load-env-file.outputs.image_name}}
          docker_username: ${{ secrets.IMAGE_REPOSITORY_USERNAME }}
          docker_password: ${{ secrets.IMAGE_REPOSITORY_PASSWORD }}
          image_version: ${{ needs.calculate-version.outputs.version }}

  update-helm-values:
    runs-on: ubuntu-latest
    needs: [push,build,calculate-version,load-env-file]
    steps:
      - uses: actions/checkout@v4
      - name: Update image tag in infrastructure repository
        uses: ./.github/actions/update-infrastructure-repository
        with:
          environment: ${{ needs.load-env-file.outputs.environment }}
          github_infra_repo_username: ${{needs.load-env-file.outputs.github_infra_repo_username}}
          github_infra_repo_name: ${{needs.load-env-file.outputs.github_infra_repo_name}}
          github_application_repo_commit_username: ${{needs.load-env-file.outputs.github_application_repo_commit_username}}
          github_application_repo_commit_user_email: ${{needs.load-env-file.outputs.github_application_repo_commit_user_email}}
          github_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          image_version: ${{ needs.calculate-version.outputs.version }}


