name: Promote acceptance workflow

on:
  release:
    types: [prereleased]

jobs:
  format_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - id: get_tag
        uses: ./.github/actions/format-tag-to-image-tag-semantic-versioning
        with:
          tag_to_format: ${{ github.event.release.tag_name }}
          
  load-env-file:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.variables.outputs.environment }}
      github_infra_repo_username: ${{ steps.variables.outputs.github_infra_repo_username }}
      github_infra_repo_name: ${{ steps.variables.outputs.github_infra_repo_name }}
      github_application_repo_commit_username: ${{ steps.variables.outputs.github_application_repo_commit_username }}
      github_application_repo_commit_user_email: ${{ steps.variables.outputs.github_application_repo_commit_user_email }}
      image_name: ${{steps.variables.outputs.image_name}}
      original_image: ${{steps.variables.outputs.original_image}}
      target_image: ${{steps.variables.outputs.target_image}}
      registry: ${{steps.variables.outputs.registry}}
    steps:
      - uses: actions/checkout@v4
      - id: variables
        uses: ./.github/actions/load-env-file
        with:
          path: ./pipeline_env_variables
          mode: acceptance
  promote:
    runs-on: ubuntu-latest
    needs: [ load-env-file,format_tag ]
    steps:
      - uses: actions/checkout@v4
      - name: push to image registry
        uses: ./.github/actions/promote-image
        with:
          registry: ${{needs.load-env-file.outputs.registry}}
          image_repository_username: ${{ github.actor }}
          image_repository_password: ${{ secrets.GITHUB_TOKEN }}
          image_version: ${{ needs.format_tag.outputs.tag }}
          original_image: ${{needs.load-env-file.outputs.original_image}}
          target_image: ${{needs.load-env-file.outputs.target_image}}
  update-helm-values:
    runs-on: ubuntu-latest
    needs: [ format_tag,load-env-file,promote ]
    steps:
      - uses: actions/checkout@v4
      - name: Update image tag in infrastructure repository
        uses: ./.github/actions/update-infrastructure-repository
        with:
          environment: ${{ needs.load-env-file.outputs.environment }}
          github_infra_repo_username: ${{needs.load-env-file.outputs.github_infra_repo_username}}
          github_infra_repo_name: ${{needs.load-env-file.outputs.github_infra_repo_name}}
          github_application_repo_commit_username: ${{needs.load-env-file.outputs.github_application_repo_commit_username}}
          github_application_repo_commit_user_email: ${{needs.load-env-file.outputs.github_application_repo_commit_user_email}}
          github_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          image_version: ${{ needs.format_tag.outputs.tag }}