version: 1
force:
  major: 0
  minor: 0
  patch: 0
  commit:
wording:
  patch:
    - update
    - initial
  minor:
    - change
    - improve
  major:
    - breaking
  release:
    - release-candidate
    - add-rc