name: Update helm values file in infra repo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  update-helm-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: lorenzoKrol/HelloWorldGitOpsInfra
          token: ${{ secrets.GHA_TOKEN }}
          
      - name: Update image tag in values.yaml
        run: |
          sed -i 's/^ *tag: .*/tag: "${{ github.sha }}"/' values.yaml

      - name: Commit and push changes to infrastructure repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/lorenzoKrol/HelloWorldGitOpsInfra.git HEAD:master

